streams:
  core:
    1: uc20
    2: core-2021v1
  ibm-gt:
    1: ibm-gt
  pro:
    2:
      fips: fips
      pro: esm
    3: advantage-2021v1
  ubuntu:
    2: primary
    3: primary-2021v1
    4: primary-2022v1
